/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package packjavacommande;

/**
 *
 * @author Abdel
 */
public class FormClient extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormClient
     */
    public FormClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        bte = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btr = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btl = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btm = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        bts = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btf = new javax.swing.JButton();
        txttc = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtdc = new javax.swing.JTextField();
        cmbnc = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tcmd = new javax.swing.JTable(){
            public java.awt.Component prepareRenderer(javax.swing.table.TableCellRenderer renderer,
                int row, int column)
            {
                java.awt.Component c = super.prepareRenderer(renderer, row, column);
                java.awt.Color color1 = java.awt.Color.GRAY;
                java.awt.Color color2 = java.awt.Color.PINK;
                java.awt.Color colorf1 = java.awt.Color.white;
                java.awt.Color colorf2 = java.awt.Color.black;
                if(!c.getBackground().equals(getSelectionBackground())) {
                    java.awt.Color coleur = (row % 2 == 0 ? color1 : color2);
                    java.awt.Color coleurf = (row % 2 == 0 ? colorf1 : colorf2);
                    c.setBackground(coleur);
                    c.setForeground(coleurf);
                    coleur = null;
                    coleurf =null;
                }
                return c;
            }
        };

        setBackground(new java.awt.Color(44, 62, 80));
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestion des clients");

        jToolBar1.setRollover(true);

        btn.setBackground(new java.awt.Color(248, 148, 6));
        btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/packjavacommande/nouveau1.png"))); // NOI18N
        btn.setToolTipText("Nouveau");
        btn.setBorderPainted(false);
        btn.setFocusable(false);
        btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn.setMaximumSize(new java.awt.Dimension(38, 34));
        btn.setMinimumSize(new java.awt.Dimension(38, 34));
        btn.setName(""); // NOI18N
        btn.setPreferredSize(new java.awt.Dimension(38, 34));
        btn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/packjavacommande/nouveau2.png"))); // NOI18N
        btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        jToolBar1.add(btn);
        jToolBar1.add(jSeparator1);

        bte.setBackground(new java.awt.Color(248, 148, 6));
        bte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/packjavacommande/enregistrer1.png"))); // NOI18N
        bte.setToolTipText("Enregistrer");
        bte.setBorderPainted(false);
        bte.setFocusable(false);
        bte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bte.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/packjavacommande/enregistrer1.png"))); // NOI18N
        bte.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/packjavacommande/enregistrer2.png"))); // NOI18N
        bte.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteActionPerformed(evt);
            }
        });
        jToolBar1.add(bte);
        jToolBar1.add(jSeparator2);

        btr.setBackground(new java.awt.Color(248, 148, 6));
        btr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/packjavacommande/recherche1.png"))); // NOI18N
        btr.setToolTipText("Rechercher");
        btr.setFocusable(false);
        btr.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btr.setMaximumSize(new java.awt.Dimension(38, 34));
        btr.setMinimumSize(new java.awt.Dimension(38, 34));
        btr.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/packjavacommande/recherche1.png"))); // NOI18N
        btr.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/packjavacommande/recherche2.png"))); // NOI18N
        btr.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btrActionPerformed(evt);
            }
        });
        jToolBar1.add(btr);
        jToolBar1.add(jSeparator3);

        btl.setBackground(new java.awt.Color(248, 148, 6));
        btl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/packjavacommande/liste1.png"))); // NOI18N
        btl.setToolTipText("Lister");
        btl.setFocusable(false);
        btl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btl.setMaximumSize(new java.awt.Dimension(38, 34));
        btl.setMinimumSize(new java.awt.Dimension(38, 34));
        btl.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/packjavacommande/lster2.png"))); // NOI18N
        btl.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/packjavacommande/lister3.png"))); // NOI18N
        btl.setVerifyInputWhenFocusTarget(false);
        btl.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlActionPerformed(evt);
            }
        });
        jToolBar1.add(btl);
        jToolBar1.add(jSeparator4);

        btm.setBackground(new java.awt.Color(248, 148, 6));
        btm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/packjavacommande/modifier1.png"))); // NOI18N
        btm.setToolTipText("Modifier");
        btm.setBorderPainted(false);
        btm.setFocusable(false);
        btm.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btm.setMaximumSize(new java.awt.Dimension(38, 34));
        btm.setMinimumSize(new java.awt.Dimension(38, 34));
        btm.setPreferredSize(new java.awt.Dimension(38, 34));
        btm.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/packjavacommande/modifier1.png"))); // NOI18N
        btm.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/packjavacommande/modifier2.png"))); // NOI18N
        btm.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmActionPerformed(evt);
            }
        });
        jToolBar1.add(btm);
        jToolBar1.add(jSeparator5);

        bts.setBackground(new java.awt.Color(248, 148, 6));
        bts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/packjavacommande/supprimer.png"))); // NOI18N
        bts.setToolTipText("Supprimer");
        bts.setBorderPainted(false);
        bts.setFocusable(false);
        bts.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bts.setMaximumSize(new java.awt.Dimension(38, 34));
        bts.setMinimumSize(new java.awt.Dimension(38, 34));
        bts.setPreferredSize(new java.awt.Dimension(38, 34));
        bts.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/packjavacommande/supprimer.png"))); // NOI18N
        bts.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/packjavacommande/supprimer2.png"))); // NOI18N
        bts.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsActionPerformed(evt);
            }
        });
        jToolBar1.add(bts);
        jToolBar1.add(jSeparator6);

        btf.setBackground(new java.awt.Color(248, 148, 6));
        btf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/packjavacommande/fermer1.png"))); // NOI18N
        btf.setToolTipText("Fermer");
        btf.setBorderPainted(false);
        btf.setFocusable(false);
        btf.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btf.setMaximumSize(new java.awt.Dimension(38, 34));
        btf.setMinimumSize(new java.awt.Dimension(38, 34));
        btf.setPreferredSize(new java.awt.Dimension(38, 34));
        btf.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/packjavacommande/fermer1.png"))); // NOI18N
        btf.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/packjavacommande/fermer2.png"))); // NOI18N
        btf.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btfActionPerformed(evt);
            }
        });
        jToolBar1.add(btf);

        txttc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttcKeyPressed(evt);
            }
        });

        jLabel7.setText("Nom du client                     :");

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setText("Information sur les clients");

        jLabel2.setText("Numéro du client                 :");
        jLabel2.setToolTipText("");

        jLabel4.setText("Prénom du client               :");

        cmbnc.setEditable(true);
        cmbnc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbncItemStateChanged(evt);
            }
        });
        cmbnc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbncMouseClicked(evt);
            }
        });
        cmbnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbncActionPerformed(evt);
            }
        });

        tcmd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tcmd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Numéro du client", "Nom du client", "Prénom du client  "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tcmd);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 1294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txttc)
                                    .addComponent(txtdc)
                                    .addComponent(cmbnc, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(jLabel1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(273, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbnc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(363, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        //nouveau();
    }//GEN-LAST:event_btnActionPerformed

    private void bteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteActionPerformed
//        try{
//            if(!recherchercle()){
//                enregistrer();
//                nouveau();
//                remplir();
//                JOptionPane.showMessageDialog(this, "La commande est bien enregistrée");
//            }
//            else
//            {
//                JOptionPane.showMessageDialog(this,"La commande existe déja");
//                cmbnc.setSelectedItem("");
//                cmbnc.requestFocus();
//            }
//        }catch(IOException |NullPointerException e){}
    }//GEN-LAST:event_bteActionPerformed

    private void btrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btrActionPerformed
//        try{
//            rechercher();
//        }catch(IOException |NullPointerException e){}
    }//GEN-LAST:event_btrActionPerformed

    private void btlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlActionPerformed
//        try{
//            lister();
//        }catch(IOException |NullPointerException e){}
    }//GEN-LAST:event_btlActionPerformed

    private void btmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmActionPerformed
//        int rep=JOptionPane.showConfirmDialog(this, "Êtes-vous sûr de modifier cet enregistrement?", "Modification", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
//        if (rep==JOptionPane.YES_OPTION){
//            modifierLigne("D:\\MonDossier\\fichierCommande.don",cmbnc.getSelectedItem().toString());
//            JOptionPane.showMessageDialog(this, "l'enregistrement est bien modifié");
//            try{
//                remplir();
//            }catch(IOException |NullPointerException e){}
//        }
    }//GEN-LAST:event_btmActionPerformed

    private void btsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsActionPerformed
//        int rep=JOptionPane.showConfirmDialog(this, "Êtes-vous sûr de supprimer cet enregistrement?", "Suppression", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
//        if (rep==JOptionPane.YES_OPTION){
//            supprimerLigne("D:\\MonDossier\\fichierCommande.don",cmbnc.getSelectedItem().toString());
//            JOptionPane.showMessageDialog(this, "l'enregistrement est bien supprimé");
//            try{
//                remplir();
//            }catch(IOException |NullPointerException e){}
//        }
    }//GEN-LAST:event_btsActionPerformed

    private void btfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btfActionPerformed
        this.hide();
    }//GEN-LAST:event_btfActionPerformed

    private void txttcKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttcKeyPressed

    }//GEN-LAST:event_txttcKeyPressed

    private void cmbncItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbncItemStateChanged
//        try{
//            rechercher();
//        }catch(IOException |NullPointerException e){}
    }//GEN-LAST:event_cmbncItemStateChanged

    private void cmbncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbncMouseClicked
//        try{
//            remplir();
//        }catch(IOException |NullPointerException e){}
    }//GEN-LAST:event_cmbncMouseClicked

    private void cmbncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbncActionPerformed

    }//GEN-LAST:event_cmbncActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bte;
    private javax.swing.JButton btf;
    private javax.swing.JButton btl;
    private javax.swing.JButton btm;
    private javax.swing.JButton btn;
    private javax.swing.JButton btr;
    private javax.swing.JButton bts;
    private javax.swing.JComboBox<String> cmbnc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tcmd;
    private javax.swing.JTextField txtdc;
    private javax.swing.JTextField txttc;
    // End of variables declaration//GEN-END:variables
}
